name: CI

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

env:
  BUILD: ${{github.workspace}}/build
  BUILD_TYPE: Release
  PARALLEL: 8

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{env.BUILD}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{env.BUILD}} --parallel ${{env.PARALLEL}} --config ${{env.BUILD_TYPE}}
