name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "diagram.svg"
          excluded_paths: "ignore,.github"
